# Generated by Django 6.0.3 on 2026-03-12 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slides_html', models.TextField()),
                ('slide_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('chunk_index', models.IntegerField()),
                ('embedding_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.document')),
            ],
            options={
                'ordering': ['document', 'page_number', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_index', models.IntegerField()),
                ('relevance_score', models.FloatField(default=0.0)),
                ('chunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.documentchunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.presentation')),
            ],
            options={
                'ordering': ['presentation', 'slide_index'],
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='source_documents',
            field=models.ManyToManyField(through='api.PresentationSource', to='api.document'),
        ),
    ]
